# Generated by Django 3.1.3 on 2020-11-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_url', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
