# Generated by Django 3.1.3 on 2020-11-15 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_url', '0002_links_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='shortened',
            field=models.CharField(max_length=50, verbose_name='short_link'),
        ),
    ]
